name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Dá permissão para o GitHub salvar a imagem no seu perfil
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    # 1. Faz login no registro do GitHub para poder salvar a imagem
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 2. Constrói e envia (push) a imagem automaticamente
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }} # Não envia se for apenas um teste de Pull Request
        tags: ghcr.io/${{ github.repository }}/warhammer-tracker:latest
